version: '3.8'

services:
  web:
    build:
      context: services/backend
      dockerfile: Dockerfile
    volumes:
      - ./services/backend:/usr/src/app
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:14
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

volumes:
  postgres_data_prod: